baseurl: /blog
paginate: 10

permalink: pretty

destination: D:/Program Files/Apache Software Foundation/Apache2.2/htdocs/blog


rp: /blog/assets/
contentImgPath: /blog/assets/cimg/
openDuoShuo: false

